spring:
  application:
    name: store-example
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      function:
        definition: process-event
      bindings:
        process-event-in-0:
          destination: ${topics.event-topic}
          consumer:
            use-native-decoding: true
            keySerde: org.apache.kafka.common.serialization.Serdes$ByteArraySerde
            valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde

topics:
  event-topic: event-input-topic
  config-topic: config-input-topic
statestore:
  name: global_config_statestore
